week_04/timetracking/config/routes.rb
Rails.application.routes.draw do

	get '/' => 'site#home'
	get '/contact' => 'site#contact'
	resources :projects do
		resources :entries
	end

	
end

week_04/timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	validates :date , presence: true
	validates :hours, :minutes , numericality: { only_integer: true }
end

week_04/timetracking/app/models/project.rb
class Project < ActiveRecord::Base

	has_many :entries
	validates :name , { uniqueness: true, presence: true , length: {maximum: 30} }
	validates :name , format: { with: /\A[a-zA-Z0-9\s]+\z/}

	def self.iron_find(id)
		where("id = ?", id).first!
	end

	def self.give_me_a_name(name)
		rows = where("name LIKE ? OR name LIKE ?", name+'-%', name).count
		if (rows == 0) 
			return name 
		else 
			return "#{name}-"+ (rows + 1).to_s
		end
	end

	def self.batch_delete(name_list)
		counter = 0
		where({name: name_list}).each do |project|
			project.destroy
			counter += 1
		end
		counter
	end

	def upcase_name!
		name.upcase!
		self.save
	end

	def self.last_created_projects(n)
		limit(n).order(created_at: :desc)
	end

	def total_hours_in_month(month, year)
		start_date = Date.new(year, month)
		end_date = Date.new(year, month).end_of_month
		entries = self.entries_of_month(month, year)
		entries.reduce(0) do | sum , entry | 
			sum += (entry.hours + entry.minutes / 60)
		end
	end

	def entries_of_month(month, year)
		start_date = Date.new(year, month)
		end_date = Date.new(year, month).end_of_month
		self.entries.where("project_id = ? AND date >= ? AND date <= ?", self.id, start_date, end_date)
	end

end

week_04/timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	
	def index
		@project = Project.find_by id: params[:project_id]
		year = Time.now.year
		month = Time.now.month
		@entry = @project.entries_of_month(month, year)
	end

	def new
		@project = Project.find params[:project_id]
		@entry = @project.entries.new
	end

	def create
		@project = Project.find(params[:project_id])
		@entry = @project.entries.new(entry_params)

		if @entry.save
			flash[:notice] = "entry created OK!"
			redirect_to project_entries_path(@project)
		else
			flash.now[:error] = "The entry couldn't be created"
			render 'new'
		end
	end
    
    def edit
    	@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
    end

    def update
    	@project = Project.find params[:project_id]
    	@entry = @project.entries.find params[:id]

    	if @entry.update_attributes(entry_params)
			flash[:notice] = "entry updated OK!"
			redirect_to project_entries_path(@project)
		else
			flash.now[:error] = "The entry couldn't be created"
			render 'edit'
		end
    end

	private
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :comment, :date)
    end


end

week_04/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
	def index
		@projects = Project.last_created_projects(10)
		if @projects.empty? 
			render 'no_projects_found', layout: 'no_project'
		end
	end

	def show
		# render 'no_projects_found' unless (@project = Project.find_by id: params[:id].to_i)
		name = params[:name]
		projects = Project.select("id, name")
		sanitized_projects = {}
		projects.each do | project |
			sanitized_projects[project.name.parameterize] = project.id
		end
		id = sanitized_projects[name]
		@project = Project.find_by id: id.to_i
	end 

end

week_04/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
  
	def home
	end

	def contact
	end

end

week_04/timetracking/app/helpers/application_helper.rb
module ApplicationHelper
	
	def flash_message
		messages = flash.keys.map do | key |
			fl(key.to_sym)
		end
		messages.join.html_safe
	end

	private
	def fl(type)
		content_tag :div, class: 'message alert' do
 			content_tag :p do
 				flash[type]
 			end
 		end
	end

end

week_04/timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

week_04/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
	def total_hours
		@project.total_hours_in_month(Time.now.month, Time.now.year)
	end
end

week_04/timetracking/app/views/entries/edit.html.erb
<% if @entry.errors.any? %>
	<ul>
	<% @entry.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
	<% end %>
</ul>
<% end %>

<%= flash_message %>

<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %><br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %><br>
	<%= f.label :comment %>
	<%= f.text_area :comment, size: "60x12" %><br>
	<%= f.label :date %>
	<%= f.text_field :date %><br>
	<%= f.submit "Save" %>
<% end %>

<%= link_to("Cancel", project_entries_path(@project)) %>

week_04/timetracking/app/views/entries/index.html.erb
<div class="container">

	<h1>Entries#index</h1>
	<%= flash_message %>

	<h2><%= @project.name %></h2>
	<p><%= @project.description %></p>

	<h3>Entries:</h3>
	<p><%= link_to("New entry", new_project_entry_path(@project)) %></p>
	<dl>
		<% @entry.each do | entry | %>
		<dt><%= entry.hours %>h <%= entry.minutes %>m</dt>
		<dd><%= entry.comment %></dd>
		<dd>Fecha: <%= entry.date %></dd>
		<dd><%= link_to("Edit", edit_project_entry_path(@project.id, entry)) %></dd>
		<% end %>
	</dl>

	<p>Total hours: <%= total_hours %></p>
	

</div><!-- /.container -->

week_04/timetracking/app/views/entries/new.html.erb
<% if @entry.errors.any? %>
	<ul>
	<% @entry.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
	<% end %>
</ul>
<% end %>

<%= flash_message %>

<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %><br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %><br>
	<%= f.label :comment %>
	<%= f.text_area :comment, size: "60x12" %><br>
	<%= f.label :date %>
	<%= f.text_field :date %><br>
	<%= f.submit "Save" %>
<% end %>

<%= link_to("Cancel", project_entries_path(@project)) %>