week_04/challenges/config/routes.rb
Rails.application.routes.draw do


  get '/' => 'site#index'
  resources :challenges do
    resources :supporters
  end
  
  get '/search' , to: 'search#index' , as: :search_string

end

week_04/challenges/app/models/challenge.rb
class Challenge < ActiveRecord::Base
	has_many :supporters
	validates :title , { uniqueness: true, presence: true , length: {maximum: 30} }
	validates :description , { presence: true , length: {minimum: 20 } }

	mount_uploader :poster, PosterUploader

	PER_PAGE = 10.0

	def self.paginate(page)
		num_pages = (Challenge.count / PER_PAGE).ceil
		offset = 0
		if page > num_pages
			page = num_pages
		elsif page < 1
			page = 1
		end

		if page
			offset = PER_PAGE * (page-1)
		end
		Challenge.limit(PER_PAGE).offset(offset)
	end

end

week_04/challenges/app/models/supporter.rb
class Supporter < ActiveRecord::Base
	belongs_to :challenge
	validates :email, {format: { with: /@/ , message: "Not a valid email" }, uniqueness: { scope: :challenge} }
end

week_04/challenges/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	rescue_from ActiveRecord::RecordNotFound ,  with: :render_404
	rescue_from ActionController::RoutingError, with: :render_404

	def render_404
		render file: "public/404", status: 404, layout: false, handlers: [:erb], formats: [:html]
	end

	before_action :load_last_challenges

	private 

	def load_last_challenges
		@last_challenges = Challenge.limit(3).order('created_at desc')
	end

end

week_04/challenges/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

	before_action :load_challenge, :only => [:edit, :show, :update, :destroy]

	def index
		@page = params[:page].to_i
		@challenges = Challenge.paginate(@page)
		@num_pages = (Challenge.count / Challenge::PER_PAGE).ceil
	end

	def new
		@challenge = Challenge.new()
	end

	def create
		@challenge = Challenge.create(challenge_params)

		if @challenge.valid?
			flash[:notice] = 'The challenge was created!'
			redirect_to challenges_path
		else
			flash.now[:error] = 'The challenge is wrong!'
			render 'new'
		end
	end

	def edit
	end

	def show
		@supporter = Supporter.new()
	end

	def update
		@challenge.update_attributes challenge_params
		render 'show'
	end

	def destroy
		@challenge.destroy
		redirect_to challenges_path
	end

	private

	def challenge_params
		params.require(:challenge).permit(:title, :description)
	end

	def load_challenge
		@challenge = Challenge.find(params[:id])
	end
end

week_04/challenges/app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def index
  	@challenges = Challenge.all

  	string = params[:string]
  	@challenges_found = Challenge.where("title LIKE '%#{string}%'")
  	render 'challenges/index'
  end
end

week_04/challenges/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

week_04/challenges/app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
	def index
	end

	def create
		@challenge = Challenge.find params[:challenge_id]
		@supporter = @challenge.supporters.create(supporter_params)
		if !@supporter.new_record?
			flash.now[:notice] = 'The supported was added!'
			ChallengeMailer.new_support(@challenge, @supporter).deliver
			redirect_to challenge_path(@challenge)
		else
			@challenge.reload
			flash[:error] = 'The email was invalid!'
			render 'challenges/show'
		end
	end

	def new
	end

	def edit
	end

	def show
	end

	def update
	end

	def destroy
	end

	private
	def supporter_params
		params.require(:supporter).permit(:email)
	end
end

week_04/challenges/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_message
		messages = flash.keys.map do | key |
			fl(key.to_sym)
		end
		messages.join.html_safe
	end

	def pagination_links
		tags = ''
		if @page !=1
			tags += link_to('← Anterior ', challenges_path(page: @page-1))
 		end

 		if @page < @num_pages
 			tags += link_to('Siguiente →', challenges_path(page: @page+1))
 		end
 		tags.html_safe
	end

	private
	def fl(type)
		content_tag :div, class: 'message alert' do
 			content_tag :p do
 				flash[type]
 			end
 		end
	end

end

week_04/challenges/app/helpers/challenges_helper.rb
module ChallengesHelper

	def challenge_errors
		if @challenge.errors.any?
			content_tag :ul do
				@challenge.errors.full_messages.collect do |error_msg|
					content_tag(:li, error_msg)
				end.join.html_safe
			end
		end
	end

	def challenges_found
		if !@challenges_found.blank?
			tags = content_tag :ul do
				@challenges_found.collect do | challenge |
					content_tag :li do
						link_to(challenge.title, challenge_path(challenge)) \
						+ ' - ' + link_to('Edit', edit_challenge_path(challenge)) \
						+ ' ' + link_to('Delete', challenge_path(challenge), method: :delete, data: {confirm: 'Are you sure?'} )
					end
				end.join.html_safe
			end
			content_tag(:h2 ,'Challenges found') + tags
		end
	end
	
	def last_challenges
		if !@last_challenges.blank?
			tags = content_tag :ul do
				@last_challenges.collect do | challenge |
					content_tag :li do
						link_to(challenge.title, challenge_path(challenge))
					end
				end.join.html_safe
			end
			content_tag(:h2 ,'Last Challenges') + tags
		end
	end
end

week_04/challenges/app/helpers/search_helper.rb
module SearchHelper
end

week_04/challenges/app/helpers/site_helper.rb
module SiteHelper
end

week_04/challenges/app/helpers/supporters_helper.rb
module SupportersHelper

	def total_supporters
		@challenge.supporters.size
	end

end

week_04/challenges/app/views/challenges/create.html.erb
<h1>Challenges#create</h1>
<p>Find me in app/views/challenges/create.html.erb</p>

week_04/challenges/app/views/challenges/destroy.html.erb
<h1>Challenges#destroy</h1>
<p>Find me in app/views/challenges/destroy.html.erb</p>

week_04/challenges/app/views/challenges/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h1>Challenges#edit</h1>
		<p>Find me in app/views/challenges/edit.html.erb</p>

		<%= flash_message %>
		<%= challenge_errors %>

		<%= form_for [@challenge] , html: { role: "form" } do |f| %>
			<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
			</div>
			<div class="form-group">
			<%= f.label :description %><br>
			<%= f.text_area :description, size: "60x12" %>
			</div>
			<%= f.submit "Save", class: "btn btn-default" %>
			<%= link_to('Cancel', challenge_path(@challenge), class: "btn btn-default") %>
		<% end %>
	</div>
</div>

week_04/challenges/app/views/challenges/index.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h1>Challenges list</h1>

		<ul>
		<% @challenges.each do | challenge | %>
			<li><%= link_to(challenge.title, challenge_path(challenge)) %> - <%= link_to('Edit', edit_challenge_path(challenge)) %> <%= link_to('Delete', challenge_path(challenge), method: :delete, data: {confirm: 'Are you sure?'} ) %> </li>
		<% end %>
		</ul>
		<%= link_to('New challenge', new_challenge_path, class: "btn btn-default") %>

		<%= pagination_links %>
	</div>

	<div class="col-xs-12 col-sm-6 col-md-4">
		<%= form_tag(search_string_path, method: :get) do %>
			<div class="form-group">
				<%= text_field_tag(:string) %>
			</div>
			<%= submit_tag("Search", class: "btn btn-default") %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<%=challenges_found%>
	</div>
</div>

week_04/challenges/app/views/challenges/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<%= flash_message %>
		<%= challenge_errors %>

		<%= form_for [@challenge] do |f| %>
			<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
			</div>
			<div class="form-group">
			<%= f.label :description %><br>
			<%= f.text_area :description, size: "60x12" %>
			</div>
			<%= f.submit "Save", class: "btn btn-default" %>
			<%= link_to('Cancel', challenges_path, class: "btn btn-default") %>
		<% end %>
	</div>
</div>

week_04/challenges/app/views/challenges/show.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h2><%= @challenge.title %></h2>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h3>Description</h3>
		<p><%= @challenge.description %></p>
		<%= link_to('Edit', edit_challenge_path(@challenge)) %>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-4">
		<h3>Support</h3>
		<%= flash_message %>
		<%= form_for [@challenge, @supporter] , html: { role: "form" } do |f| %>
			<div class="form-group">
			<%= f.text_field :email, placeholder: 'Your email' %><br>
			</div>
			<%= f.submit "Save" , class: "btn btn-default"  %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<h3>Supporters <%= total_supporters %></h3> 
		<ul class="list-unstyled">
		<% @challenge.supporters.each do | supporter | %>
			<li><%= supporter.email %></li>
		<% end %>
		</ul>
	</div>
</div>

week_04/challenges/app/views/challenges/update.html.erb
<h1>Challenges#update</h1>
<p>Find me in app/views/challenges/update.html.erb</p>

week_04/challenges/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenges</title>
  <%= stylesheet_link_tag 'components/bootstrap/dist/css/bootstrap.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
	<%= render 'layouts/partials/header' %>
	<%= yield %>
	<%= render 'layouts/partials/last_challenges' %>
	<%= render 'layouts/partials/footer' %>
</div>

</body>
</html>